"""
Regression tests for the growth-ODE friction coefficient.

These tests are committed FIRST (marked xfail) to provide an immune
indicator that the bug in src/efc/perturbation/growth.py existed, and
to establish the expected correct behaviour before the fix.

Bug: line 72 of growth.py uses coefficient (0.5 - 1.5 * Om_tilde)
in the f-form growth ODE

    f' = -f^2 - (0.5 - 1.5 * Om_tilde) * f + 1.5 * mu * Om_tilde

The correct coefficient, derived from
    D'' + [2 + d ln H/d ln a] D' - (3/2) Om_tilde D = 0
rewritten in f = d ln D / d ln a form, is (2 - 1.5 * Om_tilde):

    f' = -f^2 - (2 - 1.5 * Om_tilde) * f + 1.5 * mu * Om_tilde

At Om_tilde = 1 (matter era) this makes a factor 1.5 difference in
the friction term (0.5 wrong, -0.5 correct once signs applied).
The buggy version damps growth ~30x too weakly.

When the fix is committed, the xfail markers should be removed
(or converted to xfail(strict=True) which turns green failures into
errors, so nobody re-introduces the bug silently).
"""

import numpy as np
import pytest

from efc.perturbation.growth import growth_ode, solve_growth


@pytest.mark.xfail(
    reason="growth.py:72 friction bug — fix pending in follow-up commit",
    strict=False,
)
def test_friction_matter_era_fixed_point():
    """In matter-dominated era (Om_tilde = 1, mu = 1) with f = 1,
    the growth-rate ODE must have df/d(ln a) = 0 (fixed point)."""
    # Einstein-de Sitter: Om = 1 makes Om_tilde = 1 at any scale factor.
    ln_a = np.log(1e-3)
    f = 1.0
    df = growth_ode(ln_a, f, Omega_m=1.0, A=0.0, B=0.0)

    # Correct: -1 - (2 - 1.5) * 1 + 1.5 = 0
    # Buggy:   -1 - (0.5 - 1.5) * 1 + 1.5 = 1.5
    assert abs(df) < 1e-6, (
        f"Expected df/d(ln a) ~= 0 at matter-era fixed point, got {df:.6f}. "
        "A value near 1.5 indicates the (0.5 - 1.5 Om_tilde) friction bug."
    )


@pytest.mark.xfail(
    reason="growth.py:72 friction bug — fix pending in follow-up commit",
    strict=False,
)
def test_lcdm_growth_matches_linder_gamma():
    """Linder (2005): f(z=0) ~ Omega_m^gamma with gamma ~ 0.55 for LCDM.

    This is an *external* cross-check: the approximation does not
    depend on our solver, so it breaks the tautology risk in
    reproduce_efc.py (reference values generated by the same code).
    """
    Omega_m = 0.30
    sol = solve_growth(Omega_m=Omega_m, A=0.0, B=0.0)
    # f array is indexed by ln_a; the final entry is ln_a = 0 (z=0)
    f_z0 = float(sol["f"][-1])

    gamma = 0.55
    f_linder = Omega_m ** gamma  # ~ 0.514

    assert abs(f_z0 - f_linder) < 0.02, (
        f"LCDM f(z=0) = {f_z0:.4f} disagrees with "
        f"Linder approximation Omega_m^gamma = {f_linder:.4f} "
        "by more than 0.02. The solver and a standard approximation "
        "cannot both be right."
    )
