#!/usr/bin/env python3
"""
EFC Framework Atlas Export
===========================

Dumps the live Framework Atlas from Symbiose (Neo4j) to
schema/framework_atlas.jsonld so that the atlas is version-controlled
in Git and any Claude session (with or without Symbiose MCP access)
can query it via the EFC MCP server's atlas_query tool.

Modes:
  --dry-run   Read Symbiose, print counts, don't write file (default)
  --apply     Write the JSON-LD snapshot
  --from-stdin  Read a JSON export piped from a session that has
                Symbiose MCP access, and write the snapshot.

When run without Symbiose access (e.g. in CI or in a Claude session
without the Symbiose MCP server attached), the script exits with a
clear status message and does not overwrite the committed snapshot.

Typical flow from a Claude session that HAS Symbiose access:
  1. Call Symbiose MCP tool to export frameworks/relations/predictions
  2. Pipe the JSON into:
       python3 scripts/maintenance/efc_atlas_export.py --apply --from-stdin
  3. Commit schema/framework_atlas.jsonld

Usage:
  python3 scripts/maintenance/efc_atlas_export.py --dry-run
  python3 scripts/maintenance/efc_atlas_export.py --apply --from-stdin < export.json
"""
from __future__ import annotations
import json
import os
import sys
from datetime import datetime

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ATLAS_PATH = os.path.join(REPO, "schema", "framework_atlas.jsonld")
SCHEMA_PATH = os.path.join(REPO, "schema", "framework_atlas.schema.json")

# A JSON-LD @context must be a context document, not a JSON Schema — the old
# value pointed at framework_atlas.schema.json (and 404ed), so the atlas could
# not expand at all. Measured 2026-09-05; see scripts/maintenance/efc_ontology.py.
ATLAS_CONTEXT = {"@vocab": "https://supertedai.github.io/EFC/ontology#"}


def load_current_atlas() -> dict:
    if not os.path.exists(ATLAS_PATH):
        return {}
    with open(ATLAS_PATH) as f:
        return json.load(f)


def build_atlas_from_export(export: dict) -> dict:
    """Build atlas from a Symbiose export payload.

    Expected export shape:
      {
        "frameworks": [ {id, name, year, category, role, regimes, ...} ],
        "relations":  [ {subject, predicate, object, ...} ],
        "predictions":[ {framework, phenomenon, regime, value, ...} ]
      }
    """
    required_top = ("frameworks", "relations", "predictions")
    missing = [k for k in required_top if k not in export]
    if missing:
        raise ValueError(f"Export missing required keys: {missing}")

    return {
        "@context": ATLAS_CONTEXT,
        "@type": "FrameworkAtlas",
        "schema_version": "0.1.0",
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "source": export.get("source", "symbiose_export"),
        "provenance": export.get("provenance", {
            "note": "Generated by efc_atlas_export.py from Symbiose export."
        }),
        "frameworks": export["frameworks"],
        "relations": export["relations"],
        "predictions": export["predictions"],
    }


def validate_against_schema(atlas: dict):
    """Problems from schema/framework_atlas.schema.json (SCHEMA_PATH), or
    None when jsonschema is not installed. The export must not fail for lack
    of a validator, but must never write a snapshot the schema rejects when
    one is present — CI gate C10 re-checks the committed pair either way.
    (SCHEMA_PATH was defined and never used until 2026-09-06.)"""
    try:
        import jsonschema
    except ImportError:
        return None
    with open(SCHEMA_PATH, encoding="utf-8") as f:
        schema = json.load(f)
    cls = jsonschema.validators.validator_for(schema)
    return ["/".join(map(str, e.absolute_path)) + ": " + e.message[:160] if e.absolute_path else "<root>: " + e.message[:160]
            for e in cls(schema).iter_errors(atlas)]


def summarize(atlas: dict) -> str:
    frameworks = atlas.get("frameworks", [])
    relations = atlas.get("relations", [])
    predictions = atlas.get("predictions", [])
    categories: dict[str, int] = {}
    for fw in frameworks:
        cat = fw.get("category", "uncategorized")
        categories[cat] = categories.get(cat, 0) + 1
    lines = [
        f"frameworks: {len(frameworks)}",
        f"relations:  {len(relations)}",
        f"predictions: {len(predictions)}",
    ]
    if categories:
        lines.append("by category:")
        for cat, n in sorted(categories.items(), key=lambda kv: -kv[1]):
            lines.append(f"  {cat}: {n}")
    return "\n".join(lines)


def main() -> int:
    apply = "--apply" in sys.argv
    from_stdin = "--from-stdin" in sys.argv
    dry_run = not apply or "--dry-run" in sys.argv

    print("=" * 60)
    print("EFC FRAMEWORK ATLAS EXPORT")
    print("=" * 60)

    if from_stdin:
        raw = sys.stdin.read()
        if not raw.strip():
            print("ERROR: --from-stdin used but no data on stdin.", file=sys.stderr)
            return 2
        try:
            export = json.loads(raw)
        except json.JSONDecodeError as exc:
            print(f"ERROR: stdin is not valid JSON: {exc}", file=sys.stderr)
            return 2
        try:
            atlas = build_atlas_from_export(export)
        except ValueError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2
    else:
        # No Symbiose connector in this script — live pull must be done
        # by a session with the Symbiose MCP server and piped via stdin.
        print("No --from-stdin export provided.")
        print("This script does not hold Symbiose credentials directly.")
        print("Run from a Claude session with Symbiose MCP:")
        print("  (symbiose export) | python3 scripts/maintenance/efc_atlas_export.py --apply --from-stdin")
        atlas = load_current_atlas()
        print("\nCurrent committed atlas summary:")
        print(summarize(atlas))
        return 0

    print("\nExported atlas summary:")
    print(summarize(atlas))

    # Validate BEFORE the dry-run exit, so a dry run can say the snapshot
    # would have been refused (review finding; --apply --dry-run used to
    # write, because `dry_run and not apply` was False for that pair).
    problems = validate_against_schema(atlas)
    if problems is None:
        print("\nNote: jsonschema not installed — snapshot not validated here (CI gate C10 checks the committed pair).")
    elif problems:
        for p in problems:
            print(f"SCHEMA: {p}", file=sys.stderr)
        print(f"ERROR: export violates {os.path.relpath(SCHEMA_PATH, REPO)} ({len(problems)} problem(s)); not writing.", file=sys.stderr)
        return 1
    else:
        print(f"\nSchema OK: {os.path.relpath(SCHEMA_PATH, REPO)}")

    if dry_run:
        print("\n[DRY RUN] Not writing. Pass --apply (without --dry-run) to commit snapshot.")
        return 0

    os.makedirs(os.path.dirname(ATLAS_PATH), exist_ok=True)
    with open(ATLAS_PATH, "w") as f:
        json.dump(atlas, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"\nWrote {ATLAS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
