#!/usr/bin/env python3
"""efc_forside — generates docs/index.html from the pages that actually exist.

## Why it exists

`docs/index.html` was nine lines: a `<meta refresh>` to the Validation Ledger,
written 2026-02-13 and untouched since. The consequences, measured 2026-08-24:

* **Two of fourteen pages were unreachable** by navigating from the front page —
  `EFC_Master_v1.1.html` (the main specification) and `EFC_System_Health.html`.
  They were published only in the technical sense.
* **The target was hardcoded.** Rename the Validation Ledger and the whole site
  becomes a 404.
* **Nobody owned it.**

## Why generated and not written

A hand-written front page drifts from the pages it points at. This one reads
`docs/public/*.html`, fetches `<title>` from each, and builds the list. Add a
page and it stands on the front page at the next run. Remove one and the
link disappears — no 404.

Same pattern as the §4b register: what can be derived is derived, and CI
enforces that the file agrees with the source.

## What it does NOT do

It writes no claims about EFC. The titles come from the pages themselves, and
the order from a fixed list here — not from an assessment of what is
most important. Deciding what shall meet a reader first is an editorial
decision, and it is Morten's.

Usage:
    efc_forside.py --bygg     # write docs/index.html
    efc_forside.py --sjekk    # exit 1 if the file does not agree with the pages
"""
from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PUB = ROOT / "docs/public"
UT = ROOT / "docs/index.html"

# Order. Pages not listed here end up last, alphabetically — so a new page
# ALWAYS comes along, also when no one has updated this list. An order
# that loses pages is worse than an order that is slightly wrong.
ORDEN = [
    "EFC_Elevator_Pitch.html",
    "EFC_Master_v1.1.html",
    "EFC_Validation_Ledger.html",
    "EFC_Predictions.html",
    "EFC_Atlas.html",
    "EFC_Gap_Analysis.html",
    "EFC_Stage-IV_Data_Roadmap.html",
    "EFC_White_Paper_Series.html",
    "EFC_External_Research_Ledger.html",
    "EFC_Likelihood_Ledger.html",
    "EFC_Evaluation_Ledger.html",
    "EFC_Model_Comparison.html",
    "EFC_Changelog.html",
    "EFC_System_Health.html",
]


def _tittel(p: Path) -> str:
    t = p.read_text(encoding="utf-8", errors="replace")[:4000]
    m = re.search(r"<title>(.*?)</title>", t, re.S | re.I)
    if not m:
        return p.stem.replace("_", " ")
    s = html.unescape(re.sub(r"<[^>]+>", "", m.group(1))).strip()
    # «Energy-Flow Cosmology (EFC) – Gap Analysis» → «Gap Analysis». The prefix
    # is the same on all fourteen and carries zero information in a list.
    return re.sub(r"^Energy-Flow Cosmology\s*(\(EFC\))?\s*[–—-]\s*", "", s) or s


def bygg_html() -> str:
    sider = sorted(p.name for p in PUB.glob("*.html"))
    rekke = [s for s in ORDEN if s in sider] + [s for s in sider if s not in ORDEN]
    rader = "\n".join(
        f'      <li><a href="public/{html.escape(s)}">'
        f'{html.escape(_tittel(PUB / s))}</a></li>'
        for s in rekke)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Energy-Flow Cosmology (EFC)</title>
<link rel="stylesheet" href="efc_master.css">
</head>
<body>
  <main>
    <h1>Energy-Flow Cosmology (EFC)</h1>
    <p>Morten Magnusson &middot;
      <a href="https://orcid.org/0009-0002-4860-5095">ORCID 0009-0002-4860-5095</a>
      &middot; Symbiose Research, Sandnes, Norway</p>
    <ul>
{rader}
    </ul>
    <p><small>This page is generated by
      <code>scripts/maintenance/efc_forside.py</code> from the pages in
      <code>docs/public/</code>. Do not edit it by hand &mdash; a
      hand-written front page drifts from the pages it points at.</small></p>
  </main>
</body>
</html>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bygg", action="store_true")
    ap.add_argument("--sjekk", action="store_true")
    a = ap.parse_args()
    if not PUB.is_dir():
        print(f"[front page] cannot find {PUB}", file=sys.stderr)
        return 2
    ny = bygg_html()
    gml = UT.read_text(encoding="utf-8") if UT.exists() else ""
    if a.sjekk:
        if ny == gml:
            n = ny.count('<li><a href="public/')
            print(f"[front page] docs/index.html agrees with the {n} pages")
            return 0
        print("[front page] DEVIATION: docs/index.html does not agree with docs/public/. "
              "Run `efc_forside.py --bygg`.", file=sys.stderr)
        return 1
    if a.bygg:
        UT.write_text(ny, encoding="utf-8")
        print(f"[front page] wrote {UT.relative_to(ROOT)} — "
              f"{ny.count('<li><a href=')} pages")
        return 0
    ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
