#!/usr/bin/env python3
"""EFC page-consistency checker.

Cross-checks the following invariants on the public-facing HTML pages under
``docs/public/`` so that a Pitch- or Ledger-style internal contradiction
(e.g. "Ten probes have been falsified" alongside "8 falsified") cannot reach
production unnoticed.

Authoritative numerical truth is read from
``docs/validation-ledger/data/ledger.json`` (auto-generated by the Symbiose
pipeline). The script never rewrites HTML; it only detects drift and emits a
machine-readable report.

Invariants checked
------------------
P1.  Header banner counts on the high-traffic pages — Pitch / Ledger /
     White Paper / Roadmap / Gap Analysis — match the auto-generated
     ledger (total_public, n_falsified, planned_pipeline → derived
     active = total_public − planned_pipeline, survived = active − n_falsified).
P2.  Word-form falsified counts ("Eight probes have been falsified",
     "Ten probes ...") agree with the numeric form on the same page.
P3.  Inside the Validation Ledger executive summary, every
     "Test counts updated from X to Y across N categories
     (a + b + c + d + e)" claim has  a+b+c+d+e == Y, AND Y matches the
     ledger's current total_public (within a tolerance for historical
     intermediate updates — see HISTORICAL_RANGES).
P4.  Inside the Ledger, every "n_falsified from X to Y" claim is followed
     by either a propagation note or remains consistent with the
     pipeline's current value. A new bare claim that contradicts the
     pipeline is flagged.

Exit codes
----------
0 = clean (all invariants hold)
2 = drift detected
3 = configuration error (unable to load ledger truth)

Usage
-----
    python3 scripts/maintenance/efc_page_consistency.py            # report only
    python3 scripts/maintenance/efc_page_consistency.py --json     # machine output
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[2]
LEDGER_DATA = REPO_ROOT / "docs" / "validation-ledger" / "data" / "ledger.json"
PUBLIC_ROOT = REPO_ROOT / "docs" / "public"

# Pages that carry headline test/falsified counts. Other public pages are not
# subject to P1 (e.g. Atlas talks about frameworks, not falsified counts).
HEADER_PAGES = (
    "EFC_Elevator_Pitch.html",
    "EFC_Validation_Ledger.html",
    "EFC_White_Paper_Series.html",
    "EFC_Stage-IV_Data_Roadmap.html",
    "EFC_Gap_Analysis.html",
)

# Pages where word-form falsified counts (P2) are checked. Same set.
P2_PAGES = HEADER_PAGES

# Pages that carry the executive-summary v-update narrative (P3 / P4).
# Only the Ledger has these arithmetic claims by design.
LEDGER_PAGE = "EFC_Validation_Ledger.html"

# Historical intermediate totals that v-update paragraphs reference. These are
# allowed to differ from current total_public because they describe a past
# transition — e.g. "from 118 to 119" in v4.0-update is correct historical
# narration even though current total is 135. We only enforce that the
# arithmetic inside each paragraph is internally consistent.
WORD_TO_NUMBER = {
    "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11,
    "twelve": 12,
}

NUMBER_TO_WORD = {v: k for k, v in WORD_TO_NUMBER.items()}


@dataclass
class Issue:
    page: str
    invariant: str
    detail: str
    severity: str = "error"  # or "warning"


@dataclass
class Report:
    truth: dict = field(default_factory=dict)
    issues: list[Issue] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(i.severity == "error" for i in self.issues)


def load_truth() -> dict:
    """Authoritative numbers from the auto-generated underlay ledger."""
    if not LEDGER_DATA.exists():
        raise SystemExit(
            f"[page-consistency] truth source missing: {LEDGER_DATA}"
        )
    with LEDGER_DATA.open(encoding="utf-8") as f:
        ledger = json.load(f)
    stats = ledger.get("stats") or {}
    total = stats.get("total_public")
    planned = stats.get("planned_pipeline")
    falsified = stats.get("n_falsified")
    if total is None or planned is None or falsified is None:
        raise SystemExit(
            f"[page-consistency] ledger.json stats missing required keys:"
            f" {stats}"
        )
    active = total - planned
    survived = active - falsified
    return {
        "total_public": int(total),
        "planned_pipeline": int(planned),
        "n_falsified": int(falsified),
        "active": int(active),
        "survived": int(survived),
        "physics_test": stats.get("physics_test"),
        "consistency_check": stats.get("consistency_check"),
        "phenomenological": stats.get("phenomenological"),
        "framework_constraint": stats.get("framework_constraint"),
    }


def read_page(name: str) -> str:
    path = PUBLIC_ROOT / name
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def find_int_after(text: str, pattern: str) -> list[int]:
    return [int(m.group(1)) for m in re.finditer(pattern, text, re.IGNORECASE)]


def check_p1_header_banners(report: Report) -> None:
    """Header banner counts must match the underlay ledger."""
    truth = report.truth
    expected = {
        "total": truth["total_public"],
        "active": truth["active"],
        "survived": truth["survived"],
        "falsified": truth["n_falsified"],
        "pipeline": truth["planned_pipeline"],
    }

    patterns = {
        "active":    r"(\d{2,3})\s+active\s+probes?",
        "total":     r"\b(\d{2,3})\s+total\b",
        "survived":  r"survive[ds]?\s+(\d{2,3})\b",
        "falsified": r"\b(\d{1,3})\s+falsified\b",
        "pipeline":  r"\b(\d{1,3})\s+(?:in\s+)?pipeline\b",
    }

    for page in HEADER_PAGES:
        text = read_page(page)
        if not text:
            report.issues.append(Issue(page, "P1", "page missing"))
            continue
        for label, pat in patterns.items():
            hits = set(find_int_after(text, pat))
            if not hits:
                continue  # not all headline pages mention every count
            if hits != {expected[label]}:
                report.issues.append(
                    Issue(
                        page,
                        "P1",
                        (
                            f"{label} count drift — page reports {sorted(hits)},"
                            f" ledger says {expected[label]}"
                        ),
                    )
                )


def check_p2_word_number_consistency(report: Report) -> None:
    """Word-form (Eight, Ten, Eleven, ...) must match numeric falsified count."""
    truth = report.truth
    expected = truth["n_falsified"]

    word_pat = re.compile(
        r"\b(" + "|".join(WORD_TO_NUMBER.keys()) + r")\s+probes?\s+have\s+been\s+falsified",
        re.IGNORECASE,
    )

    for page in P2_PAGES:
        text = read_page(page)
        if not text:
            continue
        words = {m.group(1).lower() for m in word_pat.finditer(text)}
        if not words:
            continue
        word_values = {WORD_TO_NUMBER[w] for w in words}
        # Word form must match expected n_falsified from the underlay ledger
        if word_values != {expected}:
            expected_word = NUMBER_TO_WORD.get(expected, str(expected)).capitalize()
            report.issues.append(
                Issue(
                    page,
                    "P2",
                    (
                        f"word-form falsified-count drift — page contains"
                        f" {sorted(words)} but ledger says {expected}"
                        f" (expected '{expected_word}')"
                    ),
                )
            )


def check_p3_p4_ledger_arithmetic(report: Report) -> None:
    """Inside Ledger executive summary: arithmetic + n_falsified consistency."""
    text = read_page(LEDGER_PAGE)
    if not text:
        report.issues.append(Issue(LEDGER_PAGE, "P3", "page missing"))
        return

    # P3: "Test counts updated from X to Y across N categories (a + b + c + ...)"
    # We accept either "(a, b, c, d, e)" or "(a+b+c+d+e)" or comma-separated
    # with category names.
    arith_pat = re.compile(
        r"Test\s+counts?\s+updated\s+from\s+(\d{2,4})\s+to\s+(\d{2,4})"
        r"\s+across\s+(\d+)\s+categories?\s*\(([^)]+)\)",
        re.IGNORECASE,
    )
    for m in arith_pat.finditer(text):
        from_n, to_n, n_cats, body = (
            int(m.group(1)),
            int(m.group(2)),
            int(m.group(3)),
            m.group(4),
        )
        nums = [int(x) for x in re.findall(r"\b(\d+)\b", body)]
        if len(nums) != n_cats:
            report.issues.append(
                Issue(
                    LEDGER_PAGE,
                    "P3",
                    (
                        f"category-count mismatch in 'from {from_n} to {to_n}'"
                        f" — declared {n_cats} categories but found"
                        f" {len(nums)} numbers"
                    ),
                )
            )
            continue
        s = sum(nums)
        if s != to_n:
            report.issues.append(
                Issue(
                    LEDGER_PAGE,
                    "P3",
                    (
                        f"category-sum mismatch in 'from {from_n} to {to_n}'"
                        f" — sum of {nums} = {s} ≠ {to_n}"
                    ),
                )
            )

    # P4: "n_falsified from X to Y" — flag if it asserts a value different from
    # ledger truth without an immediate "remains at <truth>" or "pending
    # propagation" note.
    truth = report.truth["n_falsified"]
    nfals_pat = re.compile(
        r"n_falsified\s+(?:per\s+pipeline\s+)?from\s+(\d+)\s+to\s+(\d+)",
        re.IGNORECASE,
    )
    for m in nfals_pat.finditer(text):
        from_n, to_n = int(m.group(1)), int(m.group(2))
        if to_n == truth:
            continue
        # Look at next 200 chars for a softening note that explicitly
        # acknowledges current pipeline value.
        tail = text[m.end():m.end() + 400].lower()
        if (
            f"remains at {truth}" in tail
            or f"per pipeline remains at {truth}" in tail
            or "pending propagation" in tail
        ):
            continue
        report.issues.append(
            Issue(
                LEDGER_PAGE,
                "P4",
                (
                    f"bare 'n_falsified from {from_n} to {to_n}' contradicts"
                    f" pipeline value {truth} without a propagation note"
                ),
            )
        )


def run(json_out: bool) -> int:
    truth = load_truth()
    report = Report(truth=truth)
    check_p1_header_banners(report)
    check_p2_word_number_consistency(report)
    check_p3_p4_ledger_arithmetic(report)

    if json_out:
        out = {
            "truth": truth,
            "issues": [
                {
                    "page": i.page,
                    "invariant": i.invariant,
                    "detail": i.detail,
                    "severity": i.severity,
                }
                for i in report.issues
            ],
            "ok": report.ok,
        }
        print(json.dumps(out, indent=2))
    else:
        print(
            f"[page-consistency] truth: total={truth['total_public']}"
            f" active={truth['active']} survived={truth['survived']}"
            f" falsified={truth['n_falsified']}"
            f" pipeline={truth['planned_pipeline']}"
        )
        if report.ok:
            print("[page-consistency] all invariants hold ✓")
        else:
            print(f"[page-consistency] {len(report.issues)} issue(s):")
            for i in report.issues:
                print(f"  [{i.invariant}] {i.page}: {i.detail}")

    return 0 if report.ok else 2


def main(argv: Iterable[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="EFC page-consistency checker")
    p.add_argument("--json", action="store_true", help="machine-readable JSON output")
    args = p.parse_args(list(argv) if argv is not None else None)
    return run(json_out=args.json)


if __name__ == "__main__":
    sys.exit(main())
