"""Halo Concept -- core classes.

Models the entropic halo that forms around energy-flow structures in EFC.
The halo is not a dark matter particle distribution but an entropy shell
generated by the energy flow of baryonic structure.

Author: Morten Magnusson (ORCID 0009-0002-4860-5095)
License: CC-BY-4.0
"""

import math


class EntropyShell:
    """An individual entropy shell at a given radius.

    Parameters
    ----------
    r : float
        Radius from the centre of the structure (kpc).
    S : float
        Entropy density at this shell.
    thickness : float
        Shell thickness (kpc). Default 1.0.
    """

    def __init__(self, r: float, S: float, thickness: float = 1.0):
        self.r = r
        self.S = S
        self.thickness = thickness

    def volume(self) -> float:
        """Volume of the shell (4 pi r^2 dr)."""
        return 4.0 * math.pi * self.r**2 * self.thickness

    def total_entropy(self) -> float:
        """Total entropy content of the shell."""
        return self.S * self.volume()

    def __repr__(self) -> str:
        return f"EntropyShell(r={self.r}, S={self.S})"


class HaloProfile:
    """Radial entropy profile of a halo.

    The entropy density falls off as a power law with radius,
    modulated by a characteristic scale r_s.

    Parameters
    ----------
    S_0 : float
        Central entropy density.
    r_s : float
        Scale radius (kpc).
    alpha : float
        Power-law slope. Default 2.0.
    """

    def __init__(self, S_0: float, r_s: float, alpha: float = 2.0):
        self.S_0 = S_0
        self.r_s = r_s
        self.alpha = alpha

    def entropy_density(self, r: float) -> float:
        """Entropy density at radius r.

        S(r) = S_0 / (1 + (r/r_s)^alpha)
        """
        return self.S_0 / (1.0 + (r / self.r_s) ** self.alpha)

    def effective_mass_enhancement(self, r: float, beta: float = 0.16) -> float:
        """Effective gravitational mass enhancement mu(r) from the entropy field.

        mu(r) = 1 + beta * S(r) / S_0
        """
        return 1.0 + beta * self.entropy_density(r) / self.S_0

    def rotation_velocity(self, r: float, M_baryon: float, beta: float = 0.16) -> float:
        """Predicted rotation velocity including halo enhancement.

        v(r) = sqrt(G * M_baryon * mu(r) / r)
        Using G=1 in natural units.

        Parameters
        ----------
        r : float
            Radius (kpc).
        M_baryon : float
            Enclosed baryonic mass.
        beta : float
            EFC coupling constant.
        """
        if r <= 0:
            return 0.0
        mu = self.effective_mass_enhancement(r, beta)
        return math.sqrt(M_baryon * mu / r)

    def __repr__(self) -> str:
        return f"HaloProfile(S_0={self.S_0}, r_s={self.r_s}, alpha={self.alpha})"


class EntropicHalo:
    """Full entropic halo model for a galaxy.

    Combines a baryonic mass distribution with an entropy profile
    to produce flat rotation curves without dark matter particles.

    Parameters
    ----------
    M_baryon : float
        Total baryonic mass (solar masses, normalised).
    profile : HaloProfile
        The entropy profile of the halo.
    beta : float
        EFC coupling constant. Default 0.16.
    """

    def __init__(self, M_baryon: float, profile: HaloProfile, beta: float = 0.16):
        self.M_baryon = M_baryon
        self.profile = profile
        self.beta = beta

    def rotation_curve(self, radii: list) -> list:
        """Compute the rotation curve at a list of radii.

        Returns list of (r, v) tuples.
        """
        result = []
        for r in radii:
            v = self.profile.rotation_velocity(r, self.M_baryon, self.beta)
            result.append((r, v))
        return result

    def shell_at(self, r: float, dr: float = 1.0) -> EntropyShell:
        """Return the entropy shell at radius r."""
        S = self.profile.entropy_density(r)
        return EntropyShell(r=r, S=S, thickness=dr)

    def total_halo_entropy(self, r_max: float, n_shells: int = 100) -> float:
        """Integrate total halo entropy out to r_max."""
        dr = r_max / n_shells
        total = 0.0
        for i in range(1, n_shells + 1):
            r = i * dr
            shell = self.shell_at(r, dr)
            total += shell.total_entropy()
        return total

    def __repr__(self) -> str:
        return f"EntropicHalo(M_baryon={self.M_baryon}, beta={self.beta})"
